<a href="https://colab.research.google.com/github/superspray/study/blob/master/word_based_NLM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
data = """ Jack and Jill went up the hill
		To fetch a pail of water
		Jack fell down and broke his crown 
    And Jill came tumbling after """

In [13]:
from keras.preprocessing.text import Tokenizer


# integer encode text
tokenizer = Tokenizer()
tokenizer.fit_on_texts([data])
encoded = tokenizer.texts_to_sequences([data])[0]

tokenizer.word_index

{'a': 10,
 'after': 21,
 'and': 1,
 'broke': 16,
 'came': 19,
 'crown': 18,
 'down': 15,
 'fell': 14,
 'fetch': 9,
 'hill': 7,
 'his': 17,
 'jack': 2,
 'jill': 3,
 'of': 12,
 'pail': 11,
 'the': 6,
 'to': 8,
 'tumbling': 20,
 'up': 5,
 'water': 13,
 'went': 4}

In [14]:
# determine the vocabulary size
vocab_size = len(tokenizer.word_index) + 1
print('Vocabulary Size: %d' % vocab_size)


Vocabulary Size: 22


In [17]:
# create word -> word sequences
sequences = list()
for i in range(1, len(encoded)):
	sequence = encoded[i-1:i+1]
	sequences.append(sequence)
print('Total Sequences: %d' % len(sequences))
sequences

Total Sequences: 24


[[2, 1],
 [1, 3],
 [3, 4],
 [4, 5],
 [5, 6],
 [6, 7],
 [7, 8],
 [8, 9],
 [9, 10],
 [10, 11],
 [11, 12],
 [12, 13],
 [13, 2],
 [2, 14],
 [14, 15],
 [15, 1],
 [1, 16],
 [16, 17],
 [17, 18],
 [18, 1],
 [1, 3],
 [3, 19],
 [19, 20],
 [20, 21]]

In [20]:
import numpy as np
# split into X and y elements
sequences = np.array(sequences)
X, y = sequences[:,0],sequences[:,1]
y

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,  2, 14, 15,  1, 16,
       17, 18,  1,  3, 19, 20, 21])

In [0]:
import tensorflow as tf
import tensorflow.keras as keras
# one hot encode outputs
y = keras.utils.to_categorical(y, num_classes=vocab_size)

In [29]:
from keras import Sequential
from keras.layers import Embedding,LSTM, Dense
# define model
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=1))
model.add(LSTM(50))
model.add(Dense(vocab_size, activation='softmax'))
print(model.summary())



W0831 19:03:41.152840 140465779746688 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:66: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0831 19:03:41.209977 140465779746688 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:541: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0831 19:03:41.218148 140465779746688 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4432: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 1, 10)             220       
_________________________________________________________________
lstm_1 (LSTM)                (None, 50)                12200     
_________________________________________________________________
dense_1 (Dense)              (None, 22)                1122      
Total params: 13,542
Trainable params: 13,542
Non-trainable params: 0
_________________________________________________________________
None
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 1, 10)             220       
_________________________________________________________________
lstm_2 (LSTM)                (None, 50)                12200     
_______________________

In [30]:
# compile network
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit network
model.fit(X, y, epochs=500, verbose=2)

W0831 19:04:21.818013 140465779746688 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:793: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0831 19:04:21.858680 140465779746688 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3576: The name tf.log is deprecated. Please use tf.math.log instead.

W0831 19:04:22.027345 140465779746688 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0831 19:04:22.740028 140465779746688 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:1033: The name tf.assign_add is deprecate

Epoch 1/500
 - 1s - loss: 3.0919 - acc: 0.0000e+00
Epoch 2/500
 - 0s - loss: 3.0911 - acc: 0.0000e+00
Epoch 3/500
 - 0s - loss: 3.0904 - acc: 0.0833
Epoch 4/500
 - 0s - loss: 3.0896 - acc: 0.0833
Epoch 5/500
 - 0s - loss: 3.0889 - acc: 0.0833
Epoch 6/500
 - 0s - loss: 3.0881 - acc: 0.1250
Epoch 7/500
 - 0s - loss: 3.0873 - acc: 0.1250
Epoch 8/500
 - 0s - loss: 3.0865 - acc: 0.1250
Epoch 9/500
 - 0s - loss: 3.0857 - acc: 0.1250
Epoch 10/500
 - 0s - loss: 3.0849 - acc: 0.1250
Epoch 11/500
 - 0s - loss: 3.0841 - acc: 0.1250
Epoch 12/500
 - 0s - loss: 3.0833 - acc: 0.1250
Epoch 13/500
 - 0s - loss: 3.0824 - acc: 0.1250
Epoch 14/500
 - 0s - loss: 3.0816 - acc: 0.1250
Epoch 15/500
 - 0s - loss: 3.0807 - acc: 0.1250
Epoch 16/500
 - 0s - loss: 3.0798 - acc: 0.1250
Epoch 17/500
 - 0s - loss: 3.0789 - acc: 0.1250
Epoch 18/500
 - 0s - loss: 3.0780 - acc: 0.1250
Epoch 19/500
 - 0s - loss: 3.0770 - acc: 0.1250
Epoch 20/500
 - 0s - loss: 3.0761 - acc: 0.1250
Epoch 21/500
 - 0s - loss: 3.0751 - acc: 

In [35]:
# evaluate
in_text = 'Jack'
print(in_text)
encoded = tokenizer.texts_to_sequences([in_text])[0]
encoded = np.array(encoded)
print(encoded)
yhat = model.predict_classes(encoded, verbose=0)
for word, index in tokenizer.word_index.items():
	if index == yhat:
		print(word)

Jack
[2]
and


In [0]:
from numpy import array 
# generate a sequence from the model
def generate_seq(model, tokenizer, seed_text, n_words):
	in_text, result = seed_text, seed_text
	# generate a fixed number of words
	for _ in range(n_words):
		# encode the text as integer
		encoded = tokenizer.texts_to_sequences([in_text])[0]
		encoded = array(encoded)
		# predict a word in the vocabulary
		yhat = model.predict_classes(encoded, verbose=0)
		# map predicted word index to word
		out_word = ''
		for word, index in tokenizer.word_index.items():
			if index == yhat:
				out_word = word
				break
		# append to input
		in_text, result = out_word, result + ' ' + out_word
	return result

In [42]:
print(generate_seq(model, tokenizer, 'Jack', 6))
print(generate_seq(model, tokenizer, 'Jack', 6))
print(generate_seq(model, tokenizer, 'Jack', 6))

Jack and jill went up the hill
Jack and jill went up the hill
Jack and jill went up the hill


In [59]:
### model 2
# create line-based sequences
sequences = list()
for line in data.split('\n'):
	encoded = tokenizer.texts_to_sequences([line])[0]
	for i in range(1, len(encoded)):
		sequence = encoded[:i+1]
		sequences.append(sequence)
print('Total Sequences: %d' % len(sequences))
print(sequences)

Total Sequences: 21
[[2, 1], [2, 1, 3], [2, 1, 3, 4], [2, 1, 3, 4, 5], [2, 1, 3, 4, 5, 6], [2, 1, 3, 4, 5, 6, 7], [8, 9], [8, 9, 10], [8, 9, 10, 11], [8, 9, 10, 11, 12], [8, 9, 10, 11, 12, 13], [2, 14], [2, 14, 15], [2, 14, 15, 1], [2, 14, 15, 1, 16], [2, 14, 15, 1, 16, 17], [2, 14, 15, 1, 16, 17, 18], [1, 3], [1, 3, 19], [1, 3, 19, 20], [1, 3, 19, 20, 21]]


In [60]:
from keras.preprocessing.sequence import pad_sequences
# pad input sequences
max_length = max([len(seq) for seq in sequences])
sequences = pad_sequences(sequences, maxlen=max_length, padding='pre')
print('Max Sequence Length: %d' % max_length)

Max Sequence Length: 7


In [61]:
# split into input and output elements
sequences = array(sequences)
print(sequences)
X, y = sequences[:,:-1],sequences[:,-1]
y = keras.utils.to_categorical(y, num_classes=vocab_size)

[[ 0  0  0  0  0  2  1]
 [ 0  0  0  0  2  1  3]
 [ 0  0  0  2  1  3  4]
 [ 0  0  2  1  3  4  5]
 [ 0  2  1  3  4  5  6]
 [ 2  1  3  4  5  6  7]
 [ 0  0  0  0  0  8  9]
 [ 0  0  0  0  8  9 10]
 [ 0  0  0  8  9 10 11]
 [ 0  0  8  9 10 11 12]
 [ 0  8  9 10 11 12 13]
 [ 0  0  0  0  0  2 14]
 [ 0  0  0  0  2 14 15]
 [ 0  0  0  2 14 15  1]
 [ 0  0  2 14 15  1 16]
 [ 0  2 14 15  1 16 17]
 [ 2 14 15  1 16 17 18]
 [ 0  0  0  0  0  1  3]
 [ 0  0  0  0  1  3 19]
 [ 0  0  0  1  3 19 20]
 [ 0  0  1  3 19 20 21]]


In [62]:
# define model
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_length-1))
model.add(LSTM(50))
model.add(Dense(vocab_size, activation='softmax'))
print(model.summary())
# compile network
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit network
model.fit(X, y, epochs=500, verbose=2)

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 6, 10)             220       
_________________________________________________________________
lstm_3 (LSTM)                (None, 50)                12200     
_________________________________________________________________
dense_3 (Dense)              (None, 22)                1122      
Total params: 13,542
Trainable params: 13,542
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/500
 - 1s - loss: 3.0909 - acc: 0.0000e+00
Epoch 2/500
 - 0s - loss: 3.0897 - acc: 0.0000e+00
Epoch 3/500
 - 0s - loss: 3.0883 - acc: 0.0476
Epoch 4/500
 - 0s - loss: 3.0868 - acc: 0.0476
Epoch 5/500
 - 0s - loss: 3.0853 - acc: 0.0000e+00
Epoch 6/500
 - 0s - loss: 3.0836 - acc: 0.0952
Epoch 7/500
 - 0s - loss: 3.0820 - acc: 0.0952
Epoch 8/500
 - 0s - loss: 3.0802 -

In [63]:
# generate a sequence from a language model
def generate_seq(model, tokenizer, max_length, seed_text, n_words):
	in_text = seed_text
	# generate a fixed number of words
	for _ in range(n_words):
		# encode the text as integer
		encoded = tokenizer.texts_to_sequences([in_text])[0]
		# pre-pad sequences to a fixed length
		encoded = pad_sequences([encoded], maxlen=max_length, padding='pre')
		# predict probabilities for each word
		yhat = model.predict_classes(encoded, verbose=0)
		# map predicted word index to word
		out_word = ''
		for word, index in tokenizer.word_index.items():
			if index == yhat:
				out_word = word
				break
		# append to input
		in_text += ' ' + out_word
	return in_text
print(generate_seq(model, tokenizer, max_length-1, 'Jack', 4))
print(generate_seq(model, tokenizer, max_length-1, 'Jill', 4))

Jack fell down and broke
Jill jill came tumbling tumbling


In [74]:
##model 3
# encode 2 words -> 1 word
encoded=tokenizer.texts_to_sequences([data])[0]
sequences = list()
for i in range(2, len(encoded)):
	sequence = encoded[i-2:i+1]
	sequences.append(sequence)
print(encoded)
print(sequences)

[2, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 2, 14, 15, 1, 16, 17, 18, 1, 3, 19, 20, 21]
[[2, 1, 3], [1, 3, 4], [3, 4, 5], [4, 5, 6], [5, 6, 7], [6, 7, 8], [7, 8, 9], [8, 9, 10], [9, 10, 11], [10, 11, 12], [11, 12, 13], [12, 13, 2], [13, 2, 14], [2, 14, 15], [14, 15, 1], [15, 1, 16], [1, 16, 17], [16, 17, 18], [17, 18, 1], [18, 1, 3], [1, 3, 19], [3, 19, 20], [19, 20, 21]]


In [80]:
# pad sequences
max_length = max([len(seq) for seq in sequences])
sequences = pad_sequences(sequences, maxlen=max_length, padding='pre')
print('Max Sequence Length: %d' % max_length)
# split into input and output elements
sequences = array(sequences)
print(sequences)
X, y = sequences[:,:-1],sequences[:,-1]
y = keras.utils.to_categorical(y, num_classes=vocab_size)
print(X,y)



Max Sequence Length: 3
[[ 2  1  3]
 [ 1  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13  2]
 [13  2 14]
 [ 2 14 15]
 [14 15  1]
 [15  1 16]
 [ 1 16 17]
 [16 17 18]
 [17 18  1]
 [18  1  3]
 [ 1  3 19]
 [ 3 19 20]
 [19 20 21]]
[[ 2  1]
 [ 1  3]
 [ 3  4]
 [ 4  5]
 [ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]
 [10 11]
 [11 12]
 [12 13]
 [13  2]
 [ 2 14]
 [14 15]
 [15  1]
 [ 1 16]
 [16 17]
 [17 18]
 [18  1]
 [ 1  3]
 [ 3 19]
 [19 20]] [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0

In [81]:
# define model
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_length-1))
model.add(LSTM(50))
model.add(Dense(vocab_size, activation='softmax'))
print(model.summary())
# compile network
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit network
model.fit(X, y, epochs=500, verbose=2)

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 2, 10)             220       
_________________________________________________________________
lstm_4 (LSTM)                (None, 50)                12200     
_________________________________________________________________
dense_4 (Dense)              (None, 22)                1122      
Total params: 13,542
Trainable params: 13,542
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/500
 - 1s - loss: 3.0907 - acc: 0.0435
Epoch 2/500
 - 0s - loss: 3.0901 - acc: 0.0870
Epoch 3/500
 - 0s - loss: 3.0894 - acc: 0.0870
Epoch 4/500
 - 0s - loss: 3.0886 - acc: 0.0870
Epoch 5/500
 - 0s - loss: 3.0878 - acc: 0.0870
Epoch 6/500
 - 0s - loss: 3.0870 - acc: 0.1304
Epoch 7/500
 - 0s - loss: 3.0862 - acc: 0.1304
Epoch 8/500
 - 0s - loss: 3.0854 - acc: 0.1304

In [82]:
# evaluate model
print(generate_seq(model, tokenizer, max_length-1, 'Jack and', 5))
print(generate_seq(model, tokenizer, max_length-1, 'And Jill', 3))
print(generate_seq(model, tokenizer, max_length-1, 'fell down', 5))
print(generate_seq(model, tokenizer, max_length-1, 'pail of', 5))

Jack and jill went up the hill
And Jill went up the
fell down and broke his crown and
pail of water jack fell down and
